version: "2"
services:
  sqlserver:
    container_name: test-sqlserver
    image: 101100/integration-tests:latest
    restart: always
    ports:
      - "137-138:137-138/udp"
      - "139:139"
      - "445:445"
      - "1433:1433"
    network_mode: bridge
