version: "3"
services:
  sqlserver:
    image: 101100/integration-tests:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "137-138:137-138/udp"
      - "139:139"
      - "445:445"
      - "1433:1433"
    networks:
      - webnet
networks:
  webnet:

